server:
  port: 8888

spring:
  application:
    name: config-server
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: ${CONFIG_SERVER_SEARCH_LOCATIONS:file:/config}

management:
  endpoints:
    web:
      exposure:
        include: health
